[application]
name = "VibeCode"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "VibeCode"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
